"""add explanation column to logs

Revision ID: 20c9b3b37160
Revises: 8178a85a39d0
Create Date: 2025-12-02 18:35:38.386426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c9b3b37160'
down_revision = '8178a85a39d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_question_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('explanation', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_question_logs', schema=None) as batch_op:
        batch_op.drop_column('explanation')

    # ### end Alembic commands ###
