"""add analytics models

Revision ID: 27c8ef891b1c
Revises: d64bf7654c9b
Create Date: 2025-12-02 19:32:45.302465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27c8ef891b1c'
down_revision = 'd64bf7654c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('sessions_completed', sa.Integer(), nullable=False),
    sa.Column('questions_answered', sa.Integer(), nullable=False),
    sa.Column('correct_questions', sa.Integer(), nullable=False),
    sa.Column('avg_difficulty', sa.Float(), nullable=True),
    sa.Column('predicted_score_rw', sa.Integer(), nullable=True),
    sa.Column('predicted_score_math', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', name='uq_user_day_metric')
    )
    with op.batch_alter_table('daily_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_metrics_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_metrics_user_id'), ['user_id'], unique=False)

    op.create_table('diagnostic_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('predictor_payload', sa.JSON(), nullable=False),
    sa.Column('narrative', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnostic_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnostic_reports_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnostic_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnostic_reports_user_id'))

    op.drop_table('diagnostic_reports')
    with op.batch_alter_table('daily_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_metrics_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_metrics_day'))

    op.drop_table('daily_metrics')
    # ### end Alembic commands ###
