"""add skill mastery tables

Revision ID: 3613b47c7228
Revises: 20c9b3b37160
Create Date: 2025-12-02 18:48:40.755740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3613b47c7228'
down_revision = '20c9b3b37160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_masteries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_tag', sa.String(length=128), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('success_streak', sa.Integer(), nullable=False),
    sa.Column('last_practiced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_tag', name='uq_user_skill')
    )
    with op.batch_alter_table('skill_masteries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_masteries_skill_tag'), ['skill_tag'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_masteries_user_id'), ['user_id'], unique=False)

    op.create_table('question_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', name='uq_user_question_review')
    )
    with op.batch_alter_table('question_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_reviews_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_reviews_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_reviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_question_reviews_due_at'))

    op.drop_table('question_reviews')
    with op.batch_alter_table('skill_masteries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_masteries_user_id'))
        batch_op.drop_index(batch_op.f('ix_skill_masteries_skill_tag'))

    op.drop_table('skill_masteries')
    # ### end Alembic commands ###
