"""add learning session tables

Revision ID: 8178a85a39d0
Revises: dc87f0d73d19
Create Date: 2025-12-02 17:53:27.520941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8178a85a39d0'
down_revision = 'dc87f0d73d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('questions_assigned', sa.JSON(), nullable=False),
    sa.Column('questions_done', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('user_question_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('study_session_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('user_answer', sa.JSON(), nullable=False),
    sa.Column('time_spent_sec', sa.Integer(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.Column('viewed_explanation', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['study_session_id'], ['study_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_question_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_question_logs_study_session_id'), ['study_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_question_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_question_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_question_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_question_logs_study_session_id'))

    op.drop_table('user_question_logs')
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_sessions_user_id'))

    op.drop_table('study_sessions')
    # ### end Alembic commands ###
