"""add question import models

Revision ID: d9bfbb294685
Revises: 27c8ef891b1c
Create Date: 2025-12-02 19:40:28.162146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9bfbb294685'
down_revision = '27c8ef891b1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('source_path', sa.String(length=512), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_blocks', sa.Integer(), nullable=False),
    sa.Column('parsed_questions', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_import_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_import_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('question_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['question_import_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_drafts_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_drafts_job_id'))

    op.drop_table('question_drafts')
    with op.batch_alter_table('question_import_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_import_jobs_user_id'))

    op.drop_table('question_import_jobs')
    # ### end Alembic commands ###
