"""add question tables

Revision ID: dc87f0d73d19
Revises: 800c44b3c56a
Create Date: 2025-12-02 16:24:36.760611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc87f0d73d19'
down_revision = '800c44b3c56a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=32), nullable=False),
    sa.Column('sub_section', sa.String(length=64), nullable=True),
    sa.Column('passage_id', sa.Integer(), nullable=True),
    sa.Column('question_set_id', sa.Integer(), nullable=True),
    sa.Column('stem_text', sa.Text(), nullable=False),
    sa.Column('choices', sa.JSON(), nullable=False),
    sa.Column('correct_answer', sa.JSON(), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('irt_a', sa.Float(), nullable=True),
    sa.Column('irt_b', sa.Float(), nullable=True),
    sa.Column('skill_tags', sa.JSON(), nullable=True),
    sa.Column('estimated_time_sec', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('page', sa.String(length=32), nullable=True),
    sa.Column('index_in_set', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['passage_id'], ['passages.id'], ),
    sa.ForeignKeyConstraint(['question_set_id'], ['question_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('question_sets')
    op.drop_table('passages')
    # ### end Alembic commands ###
